import { NextRequest, NextResponse } from 'next/server'
import { supabaseAdmin } from '@/lib/supabase'
import { generateMusic } from '@/lib/lyria'
import { clipAudio } from '@/lib/audio'
import { checkRate, getClientIp } from '@/lib/rate-limit'
import { serverCapture, EVT, flushServer } from '@/lib/posthog'

export const runtime = 'nodejs'
export const maxDuration = 300

/**
 * Regenerate ONLY the audio for an existing preview. Lyrics stay put — the
 * user already approved them; they're regenerating because Lyria mispronounced
 * a word or the vibe was off.
 *
 * This is the expensive path. We cap it at MAX_REGENS_TOTAL total attempts
 * (including the initial generation) and rate-limit by IP to blunt abuse.
 */

const RATE_LIMIT_PER_HOUR = 10    // regen is audio-only; slightly higher than initial
const RATE_LIMIT_WINDOW_S = 3600

export async function POST(req: NextRequest) {
  const startedAt = Date.now()
  try {
    const body = await req.json().catch(() => null)
    const previewId = body?.previewId
    const sessionId = body?.sessionId

    if (typeof previewId !== 'string' || !previewId.startsWith('prv_')) {
      return NextResponse.json({ error: 'Invalid previewId' }, { status: 400 })
    }
    if (typeof sessionId !== 'string') {
      return NextResponse.json({ error: 'Invalid sessionId' }, { status: 400 })
    }

    const ip = getClientIp(req)

    const rate = await checkRate(ip, 'preview_regen', RATE_LIMIT_PER_HOUR, RATE_LIMIT_WINDOW_S)
    if (!rate.allowed) {
      return NextResponse.json(
        { error: 'Too many regenerations from your network. Try again in an hour.' },
        { status: 429 }
      )
    }

    // Fetch existing preview.
    const { data: preview, error: fetchErr } = await supabaseAdmin
      .from('previews')
      .select('*')
      .eq('preview_id', previewId)
      .single()

    if (fetchErr || !preview) {
      return NextResponse.json({ error: 'Preview not found' }, { status: 404 })
    }

    // Session ownership check: a preview can only be regenerated by the
    // session it was created in. Defeats copy-paste-the-id abuse.
    if (preview.session_id !== sessionId) {
      return NextResponse.json({ error: 'Preview not owned by this session' }, { status: 403 })
    }

    if (preview.purchased) {
      return NextResponse.json({ error: 'Preview already purchased' }, { status: 409 })
    }

    // M4: reject expired previews. The cleanup cron will eventually delete
    // them, but until then we refuse regen so we don't burn Lyria credits on
    // rows that are about to be garbage-collected.
    if (preview.expires_at && new Date(preview.expires_at) < new Date()) {
      return NextResponse.json(
        { error: 'Preview expired. Please start a new song.' },
        { status: 410 }
      )
    }

    if (preview.regen_count >= preview.max_regens) {
      return NextResponse.json(
        { error: 'Regeneration limit reached. Purchase to keep it, or start a new song.' },
        { status: 403 }
      )
    }

    // ─── Regenerate audio ────────────────────────────────────────────────────
    const lyricsText = (preview.sections as { label: string; lines: string[] }[])
      .map(s => `[${s.label}]\n${s.lines.join('\n')}`)
      .join('\n\n')

    const tone = preview.is_brand ? preview.brand_tone : preview.tone

    // Voice picker on the genre step. Stored on `answers.voice`. Defaults to
    // 'either' for legacy previews predating the picker.
    const voiceRaw = (preview.answers as any)?.voice
    const voice: 'male' | 'female' | 'either' =
      voiceRaw === 'male' || voiceRaw === 'female' ? voiceRaw : 'either'

    let audioUrlPreview: string | undefined = preview.audio_url_preview
    let audioPathPreview: string | undefined = preview.audio_path_preview
    let audioPathFull: string | undefined = preview.audio_path_full
    let lyriaOk = false

    try {
      const music = await generateMusic(lyricsText, preview.genre, tone, preview.title, voice)
      const fullBuffer = Buffer.from(music.audioBase64, 'base64')
      const clip = await clipAudio(fullBuffer, music.mimeType, 20)

      // Overwrite both buckets at the same preview_id path. Cache-busting
      // is done on the client with a timestamp query param.
      const fullPath = `${previewId}.mp3`
      const previewPath = `${previewId}.mp3`

      const [fullUp, previewUp] = await Promise.all([
        supabaseAdmin.storage
          .from('songs-audio-private')
          .upload(fullPath, fullBuffer, {
            contentType: music.mimeType,
            upsert: true,
          }),
        supabaseAdmin.storage
          .from('previews-audio')
          .upload(previewPath, clip.buffer, {
            contentType: clip.mimeType,
            upsert: true,
          }),
      ])

      if (!fullUp.error) audioPathFull = fullPath
      if (!previewUp.error) {
        audioPathPreview = previewPath
        const { data } = supabaseAdmin.storage.from('previews-audio').getPublicUrl(previewPath)
        audioUrlPreview = data?.publicUrl
      }
      lyriaOk = !!audioUrlPreview
    } catch (err) {
      console.error('[preview/regenerate] Lyria error:', err)
      // Don't bump regen_count if Lyria crashed — the user didn't get a new
      // attempt. If Lyria flakes repeatedly we'd rather they keep trying than
      // lock them into a bad take.
      return NextResponse.json(
        { error: 'Music generation failed. Please try again.' },
        { status: 502 }
      )
    }

    const newRegenCount = preview.regen_count + 1

    const { error: updateErr } = await supabaseAdmin
      .from('previews')
      .update({
        audio_url_preview: audioUrlPreview,
        audio_path_preview: audioPathPreview,
        audio_path_full: audioPathFull,
        regen_count: newRegenCount,
      })
      .eq('preview_id', previewId)

    if (updateErr) {
      console.error('[preview/regenerate] update failed:', updateErr)
      return NextResponse.json({ error: 'Failed to save regenerated preview' }, { status: 500 })
    }

    await supabaseAdmin.from('preview_audit').insert({
      preview_id: previewId,
      session_id: sessionId,
      email: preview.email,
      ip,
      event: 'regen',
      attempt_no: newRegenCount,
      lyria_ok: lyriaOk,
      elapsed_ms: Date.now() - startedAt,
    })

    serverCapture(sessionId, EVT.PREVIEW_REGENERATED, {
      preview_id: previewId,
      attempt_no: newRegenCount,
      regens_remaining: preview.max_regens - newRegenCount,
    })

    await flushServer()

    return NextResponse.json({
      success: true,
      preview: {
        preview_id: previewId,
        title: preview.title,
        sections: preview.sections,
        recipient_name: preview.is_brand
          ? (preview.answers as any).brand_name
          : (preview.answers as any).recipient_name,
        genre: preview.genre,
        tone,
        occasion: preview.occasion,
        is_brand: preview.is_brand,
        audio_url_preview: audioUrlPreview,
        regen_count: newRegenCount,
        max_regens: preview.max_regens,
        regens_remaining: preview.max_regens - newRegenCount,
      },
    })
  } catch (err) {
    console.error('[preview/regenerate] error:', err)
    return NextResponse.json({ error: 'Regeneration failed' }, { status: 500 })
  }
}
